### ISSUE TITLE
2.0 Roadmap

### ISSUE THREAD

**Issue by markuplab** [markuplab/catbee#38]
- [ ] Speedup bundle building
- [ ] Add devtools with time travel and mutation debugging (as side-project)
- [ ] Preserve components
- [ ] Full project documentation
- [ ] Fix some minor problems in rendering and watching
- [ ] Improve and optimize logging system (error handling)
- [ ] Update dependencies

**Comment by artem-malko** [comment]
I think, it would be nice, if you will create issue for each task from your list.

**Comment by markuplab** [comment]
https://github.com/catbee/catbee-logger - Logger as independant package
